//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnowPatternLNG.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SnowPatternLNG.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.cezeo.com/?inref=snflws.
        /// </summary>
        public static string AboutLink {
            get {
                return ResourceManager.GetString("AboutLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.cezeo.com.
        /// </summary>
        public static string AboutLinkName {
            get {
                return ResourceManager.GetString("AboutLinkName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.cezeo.com/?inref=snflwp.
        /// </summary>
        public static string AboutLinkWP {
            get {
                return ResourceManager.GetString("AboutLinkWP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Assets/secureword.en-us.png.
        /// </summary>
        public static string AdvImageWP {
            get {
                return ResourceManager.GetString("AdvImageWP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game board.
        /// </summary>
        public static string GameBoard {
            get {
                return ResourceManager.GetString("GameBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulation!.
        /// </summary>
        public static string GameCongratulation {
            get {
                return ResourceManager.GetString("GameCongratulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You won the game: {0} on the level: {1}!.
        /// </summary>
        public static string GameLevelWon {
            get {
                return ResourceManager.GetString("GameLevelWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snow Pattern.
        /// </summary>
        public static string GameName {
            get {
                return ResourceManager.GetString("GameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You won all games on the level: {0}!.
        /// </summary>
        public static string GameNextLevel {
            get {
                return ResourceManager.GetString("GameNextLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game paused, unsnap game window to Play..
        /// </summary>
        public static string GamePausedText {
            get {
                return ResourceManager.GetString("GamePausedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset game board?.
        /// </summary>
        public static string GameQuestionResetBoard {
            get {
                return ResourceManager.GetString("GameQuestionResetBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string GameQuestionTitle {
            get {
                return ResourceManager.GetString("GameQuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear board.
        /// </summary>
        public static string GameResetBoardButton {
            get {
                return ResourceManager.GetString("GameResetBoardButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern to match.
        /// </summary>
        public static string GameSampleBoard {
            get {
                return ResourceManager.GetString("GameSampleBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game:.
        /// </summary>
        public static string GameStatGame {
            get {
                return ResourceManager.GetString("GameStatGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level:.
        /// </summary>
        public static string GameStatLevel {
            get {
                return ResourceManager.GetString("GameStatLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time:.
        /// </summary>
        public static string GameStatTime {
            get {
                return ResourceManager.GetString("GameStatTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total:.
        /// </summary>
        public static string GameStatTotalTime {
            get {
                return ResourceManager.GetString("GameStatTotalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:{1}:{2}:{3}.
        /// </summary>
        public static string GameTimeFormat {
            get {
                return ResourceManager.GetString("GameTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You won the game!.
        /// </summary>
        public static string GameWon {
            get {
                return ResourceManager.GetString("GameWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game rules.
        /// </summary>
        public static string HelpPageTitle {
            get {
                return ResourceManager.GetString("HelpPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a puzzle, which goal is to create a combination of snowflakes on game board. You can see a combination you need to create on a small field on the left (sample board). Game board is on the right. You make your move by clicking on a square on game filed. All snowflakes around this square are turning. If the snowflakes was visible it becomes invisible and vice-versa. If you get stuck - use button &quot;Show Hint&quot; to see how this pattern was made. This button will highlight the squares on the sample board, w [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HelpText {
            get {
                return ResourceManager.GetString("HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show hint.
        /// </summary>
        public static string HintButton {
            get {
                return ResourceManager.GetString("HintButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string MainHelp {
            get {
                return ResourceManager.GetString("MainHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show game rules.
        /// </summary>
        public static string MainHelpDescr {
            get {
                return ResourceManager.GetString("MainHelpDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Game.
        /// </summary>
        public static string MainNewGame {
            get {
                return ResourceManager.GetString("MainNewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start New game.
        /// </summary>
        public static string MainNewGameDescr {
            get {
                return ResourceManager.GetString("MainNewGameDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume Game.
        /// </summary>
        public static string MainResumeGame {
            get {
                return ResourceManager.GetString("MainResumeGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume already started game.
        /// </summary>
        public static string MainResumeGameDescr {
            get {
                return ResourceManager.GetString("MainResumeGameDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catastrophic error :(.
        /// </summary>
        public static string MessageCatastrophicError {
            get {
                return ResourceManager.GetString("MessageCatastrophicError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error:.
        /// </summary>
        public static string MessageError {
            get {
                return ResourceManager.GetString("MessageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while reading the file.
        /// </summary>
        public static string MessageErrorFileReading {
            get {
                return ResourceManager.GetString("MessageErrorFileReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The error occurred while saving the file:.
        /// </summary>
        public static string MessageErrorWhileSave {
            get {
                return ResourceManager.GetString("MessageErrorWhileSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string MessageNo {
            get {
                return ResourceManager.GetString("MessageNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string MessageOff {
            get {
                return ResourceManager.GetString("MessageOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string MessageOk {
            get {
                return ResourceManager.GetString("MessageOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string MessageOn {
            get {
                return ResourceManager.GetString("MessageOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string MessageYes {
            get {
                return ResourceManager.GetString("MessageYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to privacy.
        /// </summary>
        public static string SettingsPanePrivacyId {
            get {
                return ResourceManager.GetString("SettingsPanePrivacyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Statement.
        /// </summary>
        public static string SettingsPanePrivacyLabel {
            get {
                return ResourceManager.GetString("SettingsPanePrivacyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.cezeo.com/company/privacy-policy/.
        /// </summary>
        public static string SettingsPanePrivacyPolicyLink {
            get {
                return ResourceManager.GetString("SettingsPanePrivacyPolicyLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string SettingsPaneSettingsId {
            get {
                return ResourceManager.GetString("SettingsPaneSettingsId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Settings.
        /// </summary>
        public static string SettingsPaneSettingsLabel {
            get {
                return ResourceManager.GetString("SettingsPaneSettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
    }
}
